name: CI/CD Pipeline

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install Dependencies
              run: npm i

            - name: Build
              run: npm run build

            - name: Generate Test Report
              run: npm run test:ci

            - name: Copy Coverage Report to Publish Directory
              run:
                  mv ./coverage/index.html ./public/coverage-report-$(date
                  +'%Y-%m-%d_%H-%M-%S_%s').html

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
                  commit_message: ${{ github.event.head_commit.message }}
